# Generated by Django 3.1 on 2020-09-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auctioner',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
