# Generated by Django 3.1 on 2020-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200929_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='numberOfBids',
            field=models.IntegerField(default=0),
        ),
    ]
