# Generated by Django 3.1 on 2020-11-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='owner',
        ),
    ]
