# Generated by Django 3.1.5 on 2021-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_like_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberOfFollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='numberOfFollowing',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
