# Generated by Django 3.1 on 2021-04-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genere',
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere_name', models.TextField(blank=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.movie')),
            ],
        ),
    ]
