# Generated by Django 3.1 on 2021-04-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20210402_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie_id',
        ),
    ]
