# Generated by Django 3.1 on 2021-04-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_actormovie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actormovie',
            old_name='actor_name',
            new_name='actor_id',
        ),
    ]
