# Generated by Django 3.1.5 on 2021-04-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_auto_20210406_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
